name: community-labeller

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:

      - uses: puppetlabs/community-labeller@maint_pr_without_label
        name: Label issues or pull requests
        with:
          label_name: community
          label_color: '5319e7'
          org_membership: puppetlabs
          ail_if_member: 'true'
          token: ${{ secrets.IAC_COMMUNITY_LABELER }}
