name: "Labeller"

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  workflow_dispatch:
    inputs:
      label_name:
        description: 'Label name'
        required: true
        default: 'community'
      label_color:
        description: 'Label color'
        required: true
        default: '5319e7'
      org_membership:
        description: 'Organization membership'
        required: true
        default: puppetlabs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Labeller Workflow
        uses: puppetlabs/cat-github-actions/.github/workflows/labeller.yml@CONT-1219_labeller
        with:
          label_name: ${{ github.event.inputs.label_name }}
          label_color: ${{ github.event.inputs.label_color }}
          org_membership: ${{ github.event.inputs.org_membership }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
