name: "labeller"

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  workflow_dispatch:

jobs:

  mend:
    uses: "puppetlabs/cat-github-actions/.github/workflows/labeller.yml@CONT-1219_labeller"
    secrets: "inherit"
