name: "Labeller"

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  workflow_dispatch:
  
jobs:
  test:
    uses: "puppetlabs/cat-github-actions/.github/workflows/labeller.yml@CONT-1219_labeller"
    with:
      label_name: community
      label_color: '5319e7'
      org_membership: puppetlabs
    secrets: "inherit"
