name: "Labeller"

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  workflow_dispatch:
    inputs:
      label_name:
        description: "Module version to be released. Must be a valid semver string. (1.2.3)"
        required: true
      label_color:
        description: "Module version to be released. Must be a valid semver string. (1.2.3)"
        required: true
      org_membership:
        description: "Module version to be released. Must be a valid semver string. (1.2.3)"
        required: true
    
jobs:
  test:
    uses: "puppetlabs/cat-github-actions/.github/workflows/labeller.yml@CONT-1219_labeller"
    with:
      label_name: "${{ github.event.inputs.label_name }}"
      label_color: "${{ github.event.inputs.label_color }}"
      org_membership: "${{ github.event.inputs.org_membership }}"
    secrets: "inherit"
